name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PI_HOST: ${{ secrets.PI_HOST }}
      PI_USER: ${{ secrets.PI_USER }}
      PI_SSH_PORT: ${{ secrets.PI_SSH_PORT }}
      PI_REPO_PATH: ${{ secrets.PI_REPO_PATH }}
      DEPLOY_DEBUG: ${{ secrets.DEPLOY_DEBUG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm
      
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:client

      - name: Generate version info (log only)
        run: |
          export RUN_NUMBER=${{ github.run_number }}
          bash scripts/generate-version.sh

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PI_SSH_PRIVATE_KEY }}

      - name: Connectivity diagnostics (optional)
        if: env.DEPLOY_DEBUG == 'true'
        run: |
          PORT=${PI_SSH_PORT:-22}
          echo "DNS resolution for host"
          getent hosts "${PI_HOST}"
          echo "TCP reachability on port ${PORT}"
          timeout 5 bash -lc "cat < /dev/null > /dev/tcp/${PI_HOST}/${PORT}" && echo "OK" || (echo "FAILED" && exit 1)

      - name: Add host key to known_hosts
        run: |
          PORT=${PI_SSH_PORT:-22}
          mkdir -p ~/.ssh
          ssh-keyscan -p "$PORT" -T 5 "$PI_HOST" >> ~/.ssh/known_hosts 2>/dev/null

      - name: Push to Pi bare repository
        run: |
          PORT=${PI_SSH_PORT:-22}
          SSH_OPTS="-o StrictHostKeyChecking=accept-new -o ConnectTimeout=10 -o ServerAliveInterval=5 -o ServerAliveCountMax=3"
          if [ "${DEPLOY_DEBUG:-}" = "true" ]; then SSH_OPTS="$SSH_OPTS -v"; fi
          export GIT_SSH_COMMAND="ssh ${SSH_OPTS}"
          git remote add pi "ssh://${PI_USER}@${PI_HOST}:${PORT}${PI_REPO_PATH}"
          git push pi HEAD:main